liquor_sales:
  outputs:
    dev:
      dataset: iowa_liquor_sales
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../.keys/sctp-dbt-1f61d505397b.json
      location: US
      method: service-account
      priority: interactive
      project: sctp-dbt
      threads: 3
      type: bigquery
  target: dev
