liquor_sales:
  outputs:
    dev:
      dataset: iowa_liquor_sales
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../.service_keys/sctp-dbt-learn-15d36f52978f.json
      location: US
      method: service-account
      priority: interactive
      project: sctp-dbt-learn
      threads: 3
      type: bigquery
  target: dev
